# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zlzp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsmc', models.CharField(max_length=100, unique=True, verbose_name='\u516c\u53f8\u540d\u79f0')),
                ('gsjj', models.TextField(max_length=254, verbose_name='\u516c\u53f8\u7b80\u4ecb')),
                ('nav_display', models.BooleanField(default=False, verbose_name='\u5bfc\u822a\u663e\u793a')),
                ('home_display', models.BooleanField(default=False, verbose_name='\u9996\u9875\u663e\u793a')),
            ],
            options={
                'ordering': ['gsmc'],
                'verbose_name': '\u62db\u8058\u516c\u53f8',
                'verbose_name_plural': '\u62db\u8058\u516c\u53f8',
            },
        ),
        migrations.CreateModel(
            name='Zwxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zwmc', models.CharField(max_length=100, verbose_name='\u804c\u4f4d\u540d\u79f0')),
                ('zwyx', models.CharField(max_length=100, verbose_name='\u804c\u4f4d\u6708\u85aa')),
                ('gzdd', models.CharField(max_length=100, verbose_name='\u5de5\u4f5c\u5730\u70b9')),
                ('gsmz', models.CharField(max_length=100, verbose_name='\u516c\u53f8\u540d\u79f0')),
                ('zwjj', models.TextField(max_length=254, verbose_name='\u804c\u4f4d\u8981\u6c42')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('published', models.BooleanField(default=True, verbose_name='\u6b63\u5f0f\u53d1\u5e03')),
                ('gsmcc', models.ManyToManyField(to='zlzp.Zlzp', verbose_name='\u62db\u8058\u516c\u53f8')),
            ],
            options={
                'ordering': ['zwmc'],
                'verbose_name': '\u804c\u4f4d\u540d\u79f0',
                'verbose_name_plural': '\u804c\u4f4d\u540d\u79f0',
            },
        ),
    ]
