# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 10:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('slug', models.CharField(db_index=True, max_length=100, verbose_name=b'\xe7\xbd\x91\xe5\x9d\x80')),
                ('content', models.TextField(blank=True, default=b'', verbose_name=b'\xe5\x86\x85\xe5\xae\xb9')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x8f\x91\xe8\xa1\xa8\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('published', models.BooleanField(default=True, verbose_name=b'\xe6\xad\xa3\xe5\xbc\x8f\xe5\x8f\x91\xe5\xb8\x83')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe4\xbd\x9c\xe8\x80\x85')),
            ],
            options={
                'verbose_name': '\u6559\u7a0b1',
                'verbose_name_plural': '\u6559\u7a0b2',
            },
        ),
        migrations.CreateModel(
            name='Colum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'\xe6\xa0\x8f\xe7\x9b\xae\xe5\x90\x8d\xe7\xa7\xb0')),
                ('slug', models.CharField(db_index=True, max_length=100, verbose_name=b'\xe6\xa0\x8f\xe7\x9b\xae\xe7\xbd\x91\xe5\x9d\x80')),
                ('intro', models.TextField(blank=True, default=b'', verbose_name=b'\xe6\xa0\x8f\xe7\x9b\xae\xe7\xae\x80\xe4\xbb\x8b')),
                ('nav_display', models.BooleanField(default=False, verbose_name=b'\xe5\xaf\xbc\xe8\x88\xaa\xe6\x98\xbe\xe7\xa4\xba')),
                ('home_display', models.BooleanField(default=False, verbose_name=b'\xe9\xa6\x96\xe9\xa1\xb5\xe6\x98\xbe\xe7\xa4\xba')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u680f\u76ee1',
                'verbose_name_plural': '\u680f\u76ee2',
            },
        ),
        migrations.AddField(
            model_name='articl',
            name='column',
            field=models.ManyToManyField(to='xinwen.Colum', verbose_name=b'\xe5\xbd\x92\xe5\xb1\x9e\xe6\xa0\x8f\xe7\x9b\xae'),
        ),
    ]
